.TH "MAKRJ.SH" 1 "2022\-12\-05" "ShellShoccar\-jpn" "Parsrs"
.\" portability
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.\" default format
.nh \" no hpyhenation
.ad l \" no justification
.\" ###########################################################################
.\" main content
.\" ###########################################################################
.SH 名称
makrj.sh \- JSONPath-value形式データをJSONテキストデータに変換
.SH 書式
.B makrj.sh
.RI [ JSONPath-value_file
.IR ... ]
.SH 説明
.B makrj.sh
コマンドは、
.BR parsrj.sh (1)
コマンドが\fBJSON\fRデータから変換して生成した
.BR JSONPath-value (5)
形式テキストデータを逆変換し、元々の
.B JSON
データを復元します。
.B JSONPath-value
データは、入力ファイル名
.I JSONPath-value_textfile
として与えるものとし、もしそれが省略されるか"\-"だった場合は、
標準入力から受け取ります。

\fBJSONPath-value\fR形式は、\fBJSON\fRデータを各種UNIXコマンドや
Tukubaiコマンドで処理するのに向いています。
そこで\fBJSON\fRデータに対し、値の修正、あるいは
